/* ===== FMIS views, part 3: messages, reports, performance, library, certificates, audit, settings, profile ===== */
'use strict';

/* ---------- messages ---------- */
function threadsFor() {
  if (!SESSION) return []; const me = SESSION.id; const out = [{ id: 'org', title: 'Everyone', icon: '📣' }];
  if (role() === 'VIEWER') return out;
  DB.projects.filter((p) => can.seeAll() || (p.team || []).includes(me)).forEach((p) => out.push({ id: 'proj:' + p.id, title: p.name, icon: '📁' }));
  DB.members.filter((m) => m.id !== me && m.status !== 'INACTIVE' && m.role !== 'VIEWER').forEach((m) => out.push({ id: 'dm:' + [me, m.id].sort().join(':'), title: m.name, icon: '👤', member: m }));
  return out;
}
const threadKey = (a, b) => 'dm:' + [a, b].sort().join(':');
VIEWS.messages = () => {
  const threads = threadsFor(); let cur = VS.sel.thread; if (!threads.find((t) => t.id === cur)) cur = window.matchMedia('(max-width:900px)').matches ? null : 'org';
  const q = (VS.q.msgs || '').toLowerCase(); const th = cur ? threads.find((t) => t.id === cur) : null;
  const list = threads.filter((t) => t.title.toLowerCase().includes(q));
  const last = (id) => DB.messages.filter((m) => m.thread === id).sort((a, b) => b.at - a.at)[0];
  const unread = (id) => DB.messages.filter((m) => m.thread === id && m.from !== SESSION.id && m.at > (DB.prefs.read[readKey(id)] || 0)).length;
  const msgs = th ? DB.messages.filter((m) => m.thread === th.id).sort((a, b) => a.at - b.at).slice(-200) : [];
  if (th) { const newest = msgs.length ? msgs[msgs.length - 1].at : 0; if (newest > (DB.prefs.read[readKey(th.id)] || 0)) { DB.prefs.read[readKey(th.id)] = newest; Store.save(DB); setTimeout(() => { $$('.nav .badge, .bottombar .badge').forEach((x) => x.remove()); $$('.nav a[data-r], .bottombar a[data-r]').forEach((a) => { const h = badgeFor(a.dataset.r); if (h) a.insertAdjacentHTML('beforeend', h); }); }, 0); } }
  return `<div class="chat ${th ? 'open' : ''}"><div class="threads card">${searchBox('msgs', 'Search chats')}${list.sort((a, b) => ((last(b.id) || {}).at || 0) - ((last(a.id) || {}).at || 0)).map((t) => { const l = last(t.id), u = unread(t.id); return `<div class="th ${cur === t.id ? 'on' : ''}" data-act="openThread" data-id="${esc(t.id)}" tabindex="0">${t.member ? avatar(t.title, 38) : `<span class="thi">${t.icon}</span>`}<div class="sp"><b>${esc(t.title)}</b><div class="muted sm">${l ? esc((l.from === SESSION.id ? 'You: ' : '') + l.text).slice(0, 44) : 'No messages yet'}</div></div>${u ? `<span class="badge">${u}</span>` : ''}</div>`; }).join('')}</div>
    <div class="conv card">${th ? `<div class="row chead"><button class="iconbtn back" data-act="closeThread" aria-label="Back">←</button><b class="sp">${esc(th.title)}</b></div><div class="msgs" id="msgs">${msgs.map((m) => `<div class="msg ${m.from === SESSION.id ? 'me' : ''} ${m.kind === 'announcement' ? 'ann' : ''}"><div class="mh"><b>${esc(S.name(m.from))}</b> <span class="muted sm">${ago(m.at)}</span>${m.kind === 'announcement' ? ' 📣' : ''}</div><div>${esc(m.text)}</div></div>`).join('') || empty('💬', 'No messages yet', 'Say hello.')}</div>
      ${can.message() && !(th.id === 'org' && role() === 'AGENT' && false) ? `<form class="composer" id="composer" data-thread="${esc(th.id)}"><input name="text" placeholder="Write a message…" autocomplete="off" aria-label="Message" required>${(th.id === 'org' || th.id.startsWith('proj:')) && can.seeAll() ? '<label class="chkl" title="Announcement"><input type="checkbox" name="ann"> 📣</label>' : ''}<button class="btn p" type="submit">Send</button></form>` : '<div class="muted sm" style="padding:10px">Viewers can read announcements only.</div>'}` : empty('💬', 'Choose a chat', 'Messages you send here reach the whole team or one person.')}</div></div>`;
};
ACT.openThread = ({ id }) => { VS.sel.thread = id; render(); const m = $('#msgs'); if (m) m.scrollTop = m.scrollHeight; };
ACT.closeThread = () => { VS.sel.thread = null; render(); };
document.addEventListener('submit', (e) => {
  const f = e.target.closest && e.target.closest('#composer'); if (!f) return; e.preventDefault();
  const text = f.text.value.trim(); if (!text || !guard(can.message())) return;
  DB.messages.push({ id: uid(), thread: f.dataset.thread, from: SESSION.id, at: Date.now(), text, kind: f.ann && f.ann.checked ? 'announcement' : 'message' }); DB.prefs.read[readKey(f.dataset.thread)] = Date.now(); commit(); render(); const m = $('#msgs'); if (m) m.scrollTop = m.scrollHeight; const i = $('#composer input'); if (i) i.focus();
});

/* ---------- reports ---------- */
VIEWS.reports = () => {
  const tab = VS.tab.rep || (role() === 'AGENT' ? 'MINE' : role() === 'VIEWER' ? 'SUM' : 'INBOX');
  const tabs = role() === 'AGENT' ? [['MINE', 'My reports'], ['SUM', 'Summary']] : role() === 'VIEWER' ? [['SUM', 'Summary']] : [['INBOX', 'Field reports'], ['SUM', 'Summary report']];
  const head = `<div class="bar row wrap">${tabsBar('rep', tabs, tab)}<span class="sp"></span>${can.report() ? '<button class="btn p" data-act="newReport">＋ Send a report</button>' : ''}</div>`;
  if (tab === 'SUM') return head + summaryPanel();
  let list = DB.reports.slice().sort((a, b) => b.at - a.at); if (tab === 'MINE') list = list.filter((r) => r.memberId === SESSION.id);
  return head + `<div class="mt">${list.map((r) => `<div class="card" style="margin-bottom:12px"><div class="row wrap"><div class="row sp">${avatar(S.name(r.memberId), 32)}<div><b>${esc(r.title)}</b><div class="muted sm">${esc(S.name(r.memberId))} · ${esc(REPORT_TYPES[r.type] || r.type)} · ${esc((S.project(r.projectId) || {}).name || 'General')} · ${ago(r.at)}</div></div></div>${stPill('report', r.status)}</div><p>${esc(r.body)}</p>${r.photo ? `<img class="subphoto" src="${esc(r.photo)}" alt="">` : ''}${r.review && r.review.note ? `<div class="alert"><span>💬</span><span><b>${esc(S.name(r.review.by))}:</b> ${esc(r.review.note)}</span></div>` : ''}${can.review() && r.status === 'SENT' ? `<button class="btn s p" data-act="reviewReport" data-id="${esc(r.id)}" style="margin-top:8px">Review</button>` : ''}</div>`).join('') || empty('📊', 'No reports yet', can.report() ? 'Send a daily report, an incident or a success story.' : '')}</div>`;
};
ACT.newReport = () => {
  if (!guard(can.report())) return;
  modal({ title: '＋ Send a report', wide: true, submit: 'Send report', body: `${F([{ name: 'type', label: 'Type', options: options(REPORT_TYPES), value: 'DAILY' }, { name: 'projectId', label: 'Project', options: [['', '(general)'], ...memberOpts(DB.projects)] }, { name: 'title', label: 'Title', required: true, full: true }, { name: 'body', label: 'What happened?', type: 'textarea', required: true, full: true, rows: 5 }])}<div class="full" style="margin-top:10px"><label class="f">Photo (optional)</label><input type="hidden" name="f_rp" value=""><div class="photobox"><img id="f_rp_img" alt="" hidden><label class="btn s p" style="cursor:pointer">📷 Add a photo<input type="file" accept="image/*" capture="environment" hidden data-photo="f_rp"></label></div></div>`,
    onSubmit: (v) => { DB.reports.push({ id: uid(), memberId: SESSION.id, projectId: v.projectId || null, type: v.type, title: v.title.trim(), body: v.body.trim(), photo: v.f_rp || null, at: Date.now(), status: 'SENT', review: null }); audit('Report sent', v.title); commit(); refresh(); toast('Report sent'); } });
};
ACT.reviewReport = ({ id }) => { const r = DB.reports.find((x) => x.id === id); modal({ title: 'Review: ' + esc(r.title), body: `<p class="muted">${esc(r.body)}</p>${F([{ name: 'note', label: 'Your reply (optional)', type: 'textarea', full: true, rows: 3 }])}`, submit: 'Mark as reviewed', onSubmit: (v) => { r.status = 'REVIEWED'; r.review = { by: SESSION.id, at: Date.now(), note: (v.note || '').trim() }; audit('Report reviewed', r.title); commit(); refresh(); toast('Reviewed'); } }); };

function reportData(from, to, projectId) {
  const inR = (t) => t >= from && t < to + DAY; const forms = DB.forms.filter((f) => !projectId || f.projectId === projectId).map((f) => f.id);
  const subs = DB.submissions.filter((s) => s.status !== 'DRAFT' && inR(s.at) && (!projectId || forms.includes(s.formId) || s.projectId === projectId)); const tasks = DB.tasks.filter((t) => !projectId || t.projectId === projectId);
  const byAgent = DB.members.filter((m) => m.role === 'AGENT' || m.role === 'SUPERVISOR').map((m) => { const s = subs.filter((x) => x.memberId === m.id); return { m, n: s.length, appr: s.filter((x) => x.status === 'APPROVED').length, rej: s.filter((x) => x.status === 'REJECTED').length, days: new Set(DB.checkins.filter((c) => c.memberId === m.id && c.type === 'IN' && inR(c.at)).map((c) => dayStart(c.at))).size }; }).filter((x) => x.n || x.days);
  const days = []; for (let d = dayStart(from); d <= to && days.length < 62; d += DAY) days.push({ l: fdate(d, { day: 'numeric', month: 'short' }).replace(/ \d{4}$/, ''), v: subs.filter((s) => dayStart(s.at) === d).length });
  return { subs, tasks, byAgent, days, rate: S.approvalRate(subs) };
}
function summaryPanel() {
  const to = fromInputDate(VS.sel.repTo || toInputDate(Date.now())), from = fromInputDate(VS.sel.repFrom || toInputDate(Date.now() - 29 * DAY)), pid = VS.sel.repProj || ''; const r = reportData(from, to, pid);
  return `<div class="card mt"><div class="row wrap" style="gap:10px"><label class="f">From <input type="date" data-sel="repFrom" value="${esc(VS.sel.repFrom || toInputDate(Date.now() - 29 * DAY))}"></label><label class="f">To <input type="date" data-sel="repTo" value="${esc(VS.sel.repTo || toInputDate(Date.now()))}"></label><label class="f">Project <select data-sel="repProj"><option value="">All projects</option>${DB.projects.map((p) => `<option value="${esc(p.id)}" ${pid === p.id ? 'selected' : ''}>${esc(p.name)}</option>`).join('')}</select></label><span class="sp"></span><button class="btn p" data-act="printSummary">🖨 Print or save as PDF</button>${can.seeAll() ? '<button class="btn" data-act="exportSummary">⬇ CSV</button>' : ''}</div></div>
  <div class="grid g4 mt">${kpi('a', '📥', 'Submissions', r.subs.length, 'in this period')}${kpi('b', '✅', 'Approved', r.subs.filter((s) => s.status === 'APPROVED').length, r.rate == null ? 'not reviewed yet' : r.rate + '% of reviewed')}${kpi('c', '📋', 'Tasks done', `${r.tasks.filter((t) => t.status === 'DONE').length}/${r.tasks.length}`, 'in scope')}${kpi('d', '📍', 'Field days', r.byAgent.reduce((a, x) => a + x.days, 0), 'check-ins')}</div>
  <div class="card mt"><h3>Submissions per day</h3>${Charts.bars(r.days.slice(-31))}</div>
  ${can.seeAll() ? `<div class="card mt tw"><h3>By person</h3><table><thead><tr><th>Person</th><th class="r">Submitted</th><th class="r">Approved</th><th class="r">Rejected</th><th class="r">Field days</th></tr></thead><tbody>${r.byAgent.map((x) => `<tr><td>${esc(x.m.name)}</td><td class="r">${x.n}</td><td class="r">${x.appr}</td><td class="r">${x.rej}</td><td class="r">${x.days}</td></tr>`).join('') || '<tr><td colspan="5" class="muted">No activity in this period.</td></tr>'}</tbody></table></div>` : ''}`;
}
document.addEventListener('change', (e) => { const el = e.target.closest && e.target.closest('[data-sel]'); if (el && /^rep/.test(el.dataset.sel)) { VS.sel[el.dataset.sel] = el.value; render(); } });
ACT.printSummary = () => {
  const to = fromInputDate(VS.sel.repTo || toInputDate(Date.now())), from = fromInputDate(VS.sel.repFrom || toInputDate(Date.now() - 29 * DAY)), pid = VS.sel.repProj || ''; const r = reportData(from, to, pid); const p = S.project(pid);
  printDoc('FMIS-summary-report.pdf', 'Summary report', `<p class="muted">${fdate(from)} to ${fdate(to)} · ${esc(p ? p.name : 'All projects')}</p><div class="kpis"><div class="k">Submissions<b>${r.subs.length}</b></div><div class="k">Approved<b>${r.subs.filter((s) => s.status === 'APPROVED').length}</b></div><div class="k">Approval rate<b>${r.rate == null ? '—' : r.rate + '%'}</b></div><div class="k">Tasks done<b>${r.tasks.filter((t) => t.status === 'DONE').length}/${r.tasks.length}</b></div></div>
    <h2>Submissions by person</h2><table><tr><th>Person</th><th class="r">Submitted</th><th class="r">Approved</th><th class="r">Rejected</th><th class="r">Field days</th></tr>${r.byAgent.map((x) => `<tr><td>${esc(x.m.name)}</td><td class="r">${x.n}</td><td class="r">${x.appr}</td><td class="r">${x.rej}</td><td class="r">${x.days}</td></tr>`).join('')}</table>
    <h2>Projects</h2><table><tr><th>Project</th><th>Status</th><th class="r">Progress</th><th class="r">Submissions</th></tr>${DB.projects.filter((x) => !pid || x.id === pid).map((x) => { const pr = S.projectProgress(x); return `<tr><td>${esc(x.name)}</td><td>${esc(STATUS.project[x.status])}</td><td class="r">${pr.pct}%</td><td class="r">${pr.subs}${x.target ? ' / ' + x.target : ''}</td></tr>`; }).join('')}</table>`);
};
ACT.exportSummary = async () => { const to = fromInputDate(VS.sel.repTo || toInputDate(Date.now())), from = fromInputDate(VS.sel.repFrom || toInputDate(Date.now() - 29 * DAY)); const r = reportData(from, to, VS.sel.repProj || ''); await exportCSV('summary-by-person.csv', [['Person', 'Submitted', 'Approved', 'Rejected', 'Field days'], ...r.byAgent.map((x) => [x.m.name, x.n, x.appr, x.rej, x.days])]); toast('Exported'); };

/* ---------- performance ---------- */
VIEWS.performance = () => {
  const rows = DB.members.filter((m) => m.role === 'AGENT' && m.status !== 'INACTIVE').map((m) => ({ m, sc: S.score(m) })).sort((a, b) => b.sc.total - a.sc.total);
  return `<div class="bar row wrap"><span class="muted sm">Score = quality 35% · output 25% · task reliability 20% · attendance 20%</span><span class="sp"></span><button class="btn" data-act="exportPerf">⬇ Export</button></div>
  <div class="card mt tw"><table><thead><tr><th>#</th><th>Field agent</th><th class="r">Score</th><th>Quality</th><th>Output</th><th>Tasks</th><th>Attendance</th><th class="r">Submissions</th></tr></thead><tbody>${rows.map((x, i) => `<tr><td><b>${i + 1}</b></td><td><div class="row">${avatar(x.m.name, 30)}<b>${esc(x.m.name)}</b></div></td><td class="r"><b>${x.sc.total}</b></td><td style="min-width:90px">${bar(x.sc.quality)}</td><td style="min-width:90px">${bar(x.sc.output)}</td><td style="min-width:90px">${bar(x.sc.reliability)}</td><td style="min-width:90px">${bar(x.sc.attendance)}</td><td class="r">${x.sc.submissions}</td></tr>`).join('') || `<tr><td colspan="8">${empty('🏆', 'No field agents yet')}</td></tr>`}</tbody></table></div>`;
};
ACT.exportPerf = async () => { await exportCSV('performance.csv', [['Rank', 'Agent', 'Score', 'Quality', 'Output', 'Tasks', 'Attendance', 'Submissions'], ...DB.members.filter((m) => m.role === 'AGENT').map((m) => ({ m, sc: S.score(m) })).sort((a, b) => b.sc.total - a.sc.total).map((x, i) => [i + 1, x.m.name, x.sc.total, x.sc.quality, x.sc.output, x.sc.reliability, x.sc.attendance, x.sc.submissions])]); toast('Exported'); };

/* ---------- library ---------- */
VIEWS.library = () => {
  const q = (VS.q.lib || '').toLowerCase(); const cats = [...new Set(DB.library.map((l) => l.category || 'General'))]; const cf = VS.tab.libCat || 'ALL';
  const list = DB.library.filter((l) => (cf === 'ALL' || (l.category || 'General') === cf) && (l.title + ' ' + (l.body || '')).toLowerCase().includes(q));
  return `<div class="bar row wrap">${searchBox('lib', 'Search the library')}${tabsBar('libCat', [['ALL', 'All'], ...cats.map((c) => [c, c])], cf)}<span class="sp"></span>${can.manageWork() ? '<button class="btn p" data-act="newLib">＋ Add item</button>' : ''}</div>
  <div class="mt grid g2">${list.map((l) => `<div class="card"><div class="row"><span style="font-size:26px">${l.kind === 'link' ? '🔗' : '📄'}</span><div class="sp"><b>${esc(l.title)}</b><div class="muted sm">${esc(l.category || 'General')} · ${fdate(l.at)}</div></div></div><p class="muted sm" style="margin:8px 0">${esc((l.body || l.url || '').slice(0, 140))}</p><div class="row wrap" style="gap:8px"><button class="btn s p" data-act="openLib" data-id="${esc(l.id)}">Open</button>${can.manageWork() ? `<button class="btn s" data-act="editLib" data-id="${esc(l.id)}">Edit</button><button class="btn s r" data-act="delLib" data-id="${esc(l.id)}">Delete</button>` : ''}</div></div>`).join('') || `<div class="full">${empty('📚', 'The library is empty', 'Guides, links and notes for the team appear here.')}</div>`}</div>`;
};
const libFields = (l = {}) => [{ name: 'title', label: 'Title', required: true, full: true, value: l.title || '' }, { name: 'category', label: 'Category', value: l.category || 'Guides' }, { name: 'kind', label: 'Type', options: [['note', 'Note or guide (text)'], ['link', 'Web link']], value: l.kind || 'note' }, { name: 'url', label: 'Web address (for a link)', value: l.url || '', full: true, placeholder: 'https://…' }, { name: 'body', label: 'Text (for a note)', type: 'textarea', full: true, rows: 6, value: l.body || '' }];
ACT.newLib = () => { if (!guard(can.manageWork())) return; modal({ title: '＋ Add to the library', wide: true, body: F(libFields()), onSubmit: (v) => { DB.library.push({ id: uid(), title: v.title.trim(), category: v.category.trim() || 'General', kind: v.kind, url: v.url.trim(), body: v.body, at: Date.now(), by: SESSION.id }); audit('Library item added', v.title); commit(); refresh(); toast('Added'); } }); };
ACT.editLib = ({ id }) => { const l = DB.library.find((x) => x.id === id); if (!guard(can.manageWork())) return; modal({ title: 'Edit item', wide: true, body: F(libFields(l)), onSubmit: (v) => { Object.assign(l, { title: v.title.trim(), category: v.category.trim() || 'General', kind: v.kind, url: v.url.trim(), body: v.body, at: Date.now() }); commit(); refresh(); toast('Saved'); } }); };
ACT.delLib = ({ id }) => { if (!guard(can.manageWork())) return; confirmBox('Delete this library item?', () => { DB.library = DB.library.filter((x) => x.id !== id); commit(); refresh(); closeModal(); }, 'Delete', true); };
ACT.openLib = ({ id }) => { const l = DB.library.find((x) => x.id === id); if (l.kind === 'link' && l.url) { if (window.api && window.api.openExternal) window.api.openExternal(l.url); else window.open(l.url, '_blank', 'noopener'); return; } modal({ title: esc(l.title), wide: true, cancel: 'Close', body: `<div style="white-space:pre-wrap;line-height:1.6">${esc(l.body || 'No text.')}</div>` }); };

/* ---------- certificates ---------- */
VIEWS.certificates = () => `<div class="bar row wrap"><span class="muted sm">Recognise training and good work. Certificates can be printed or saved as PDF.</span><span class="sp"></span>${can.manageWork() ? '<button class="btn p" data-act="issueCert">＋ Issue a certificate</button>' : ''}</div>
  <div class="card mt tw"><table><thead><tr><th>Serial</th><th>Awarded to</th><th>For</th><th>Date</th><th></th></tr></thead><tbody>${DB.certificates.slice().sort((a, b) => b.at - a.at).map((c) => `<tr><td>${esc(c.serial)}</td><td><b>${esc(S.name(c.memberId))}</b></td><td>${esc(c.title)}</td><td>${fdate(c.at)}</td><td class="r"><button class="btn s" data-act="printCert" data-id="${esc(c.id)}">🖨 Print</button></td></tr>`).join('') || `<tr><td colspan="5">${empty('🎓', 'No certificates yet')}</td></tr>`}</tbody></table></div>`;
ACT.issueCert = ({ id }) => {
  if (!guard(can.manageWork())) return; closeModal();
  modal({ title: '🎓 Issue a certificate', body: F([{ name: 'memberId', label: 'Awarded to', options: memberOpts(DB.members.filter((m) => m.role !== 'VIEWER')), value: id || '', full: true }, { name: 'title', label: 'Title', required: true, full: true, placeholder: 'e.g. Completion of enumerator training' }, { name: 'detail', label: 'Details (optional)', type: 'textarea', full: true, rows: 3 }]), submit: 'Issue',
    onSubmit: (v) => { DB.seq.cert = (DB.seq.cert || 0) + 1; const c = { id: uid(), memberId: v.memberId, title: v.title.trim(), detail: v.detail, issuedBy: SESSION.id, at: Date.now(), serial: 'CERT-' + String(DB.seq.cert).padStart(4, '0') }; DB.certificates.push(c); audit('Certificate issued', `${c.serial} to ${S.name(c.memberId)}`); commit(); refresh(); toast('Certificate issued'); setTimeout(() => ACT.printCert({ id: c.id }), 200); } });
};
ACT.printCert = ({ id }) => {
  const c = DB.certificates.find((x) => x.id === id); if (!c) return;
  printDoc(`${c.serial}.pdf`, 'Certificate', `<html><head><meta charset="utf-8"><title>${esc(c.serial)}</title><style>${PRINT_CSS}@page{size:A4 landscape;margin:12mm}</style></head><body><div class="cert"><img src="${LOGO_DATA}" alt="" width="70" height="70"><h1>Certificate</h1><div class="muted">${esc(DB.org.name)}</div><p style="margin-top:28px">This certifies that</p><div class="big">${esc(S.name(c.memberId))}</div><p>${esc(c.title)}</p>${c.detail ? `<p class="muted">${esc(c.detail)}</p>` : ''}<p class="muted" style="margin-top:34px">Issued ${fdate(c.at)} by ${esc(S.name(c.issuedBy))} · Serial ${esc(c.serial)}</p></div></body></html>`, true);
};

/* ---------- audit ---------- */
VIEWS.audit = () => {
  const q = (VS.q.aud || '').toLowerCase(); const list = DB.audit.filter((a) => (a.action + ' ' + a.details + ' ' + a.by).toLowerCase().includes(q)).slice(0, 300);
  return `<div class="bar row wrap">${searchBox('aud', 'Search the log')}<span class="sp"></span><button class="btn" data-act="exportAudit">⬇ Export</button></div><div class="card mt tw"><table><thead><tr><th>When</th><th>Who</th><th>What</th><th>Details</th></tr></thead><tbody>${list.map((a) => `<tr><td>${fdt(a.at)}</td><td>${esc(a.by)}</td><td><b>${esc(a.action)}</b></td><td class="muted">${esc(a.details)}</td></tr>`).join('') || `<tr><td colspan="4">${empty('🛡️', 'Nothing logged yet')}</td></tr>`}</tbody></table></div>`;
};
ACT.exportAudit = async () => { await exportCSV('audit-log.csv', [['When', 'Who', 'Action', 'Details'], ...DB.audit.map((a) => [fdt(a.at), a.by, a.action, a.details])]); toast('Exported'); };

/* ---------- settings and profile ---------- */
VIEWS.settings = () => {
  const o = DB.org; const adm = can.admin();
  return `<div class="grid g2"><div>${adm ? `<div class="card"><h3>🏢 Workspace</h3><form id="orgform">${F([{ name: 'name', label: 'Name', value: o.name, full: true, required: true }, { name: 'sector', label: 'Sector', value: o.sector || '' }, { name: 'country', label: 'Country', value: o.country || '' }, { name: 'contact', label: 'Contact (phone or email)', value: o.contact || '', full: true }, { name: 'about', label: 'About', type: 'textarea', value: o.about || '', full: true, rows: 2 }])}<div class="mt"><button class="btn p" data-act="saveOrg" type="button">Save</button></div></form></div>` : `<div class="card"><h3>🏢 ${esc(o.name)}</h3><p class="muted">${esc(o.about || '')}</p></div>`}
    <div class="card mt"><h3>🎨 Appearance and language</h3><div class="row wrap"><button class="btn" data-act="toggleTheme">🌓 Dark or light</button><button class="btn" data-act="langCycle">🌍 ${LANGS[LANG]}</button></div></div>
    <div class="card mt"><h3>🔒 Roles and access</h3>${ROLE_ORDER.map((r) => `<div class="li"><b>${roleTag(r)}</b><div class="muted sm">${ROLE_INFO[r]}</div></div>`).join('')}</div></div>
    <div>${window.Cloud && !DB.demo ? Cloud.card() : (DB.demo ? '<div class="card"><h3>☁️ Cloud sync</h3><p class="muted">Cloud sync is off in the demo. Create your own workspace to use it.</p></div>' : '')}
    ${adm ? `<div class="card mt"><h3>💾 Backup</h3><p class="muted">Save a copy of everything on this device. Restore it on another device or after a reset.</p><div class="row wrap"><button class="btn p" data-act="backup">Save backup</button></div></div>
    <div class="card mt"><h3>⚠️ Danger zone</h3><p class="muted">Erase this workspace from this device. If cloud sync is on, the cloud copy stays. Make a backup first.</p><button class="btn r" data-act="wipe">Erase all data here</button></div>` : ''}</div></div>`;
};
ACT.saveOrg = () => { if (!guard(can.admin())) return; const v = Object.fromEntries(new FormData($('#orgform')).entries()); Object.assign(DB.org, { name: v.name.trim(), sector: v.sector, country: v.country, contact: v.contact, about: v.about }); audit('Workspace settings updated', ''); commit(); shell(); toast('Saved'); };
ACT.backup = async () => { const c = JSON.stringify(Object.assign({}, DB, { cloud: undefined }), null, 1); const name = `fmis-backup-${toInputDate(Date.now())}.json`; if (window.api && window.api.exportFile) await window.api.exportFile({ name, content: c, filters: [{ name: 'Backup', extensions: ['json'] }] }); else { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([c])); a.download = name; document.body.appendChild(a); a.click(); setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 500); } audit('Backup saved', ''); commit(); toast('Backup saved'); };
ACT.wipe = () => { if (!guard(can.admin())) return; modal({ title: '⚠️ Erase all data', danger: true, submit: 'Erase everything', body: '<p>This deletes the workspace from this device. Type <b>ERASE</b> to confirm.</p>' + F([{ name: 'c', label: 'Confirmation', full: true }]), onSubmit: (v) => { if (v.c !== 'ERASE') { toast('Type ERASE to confirm.', true); return false; } DB = null; SESSION = null; if (window.api && window.api.save) window.api.save(null); else localStorage.removeItem('fmis-db'); welcome(); } }); };

VIEWS.profile = () => {
  const m = SESSION; const sc = m.role === 'AGENT' ? S.score(m) : null; const certs = DB.certificates.filter((c) => c.memberId === m.id);
  return `<div class="grid g2"><div><div class="card c">${avatar(m.name, 90)}<h2 style="margin-top:12px">${esc(m.name)}</h2>${roleTag(m.role)}<div class="list mt" style="text-align:left">${[['💼', 'Position', m.title], ['📍', 'Region', m.region], ['📞', 'Phone', m.phone], ['✉️', 'Email', m.email]].map(([i, l, v]) => `<div class="row li"><span>${i}</span><span class="muted sp">${l}</span><b>${esc(v || '—')}</b></div>`).join('')}</div></div>
    <div class="card mt"><h3>🔐 Change my PIN</h3><form id="pinform">${F([{ name: 'old', label: 'Current PIN', type: 'password' }, { name: 'nw', label: 'New PIN (4 digits)', type: 'password' }])}<div class="mt"><button class="btn p" type="button" data-act="changePin">Update PIN</button></div></form></div></div>
    <div>${sc ? `<div class="card"><h3>🏆 My performance</h3><div class="row" style="justify-content:space-around">${Charts.ring(sc.total, sc.total, 'score')}${Charts.ring(sc.quality, sc.quality + '%', 'quality', 'var(--amber)')}</div><div class="list mt">${[['📥', 'Submissions', sc.submissions], ['✅', 'Task completion', sc.reliability + '%'], ['📍', 'Attendance (30 days)', S.daysPresent(m.id) + ' days']].map(([i, l, v]) => `<div class="row li"><span>${i}</span><span class="muted sp">${l}</span><b>${v}</b></div>`).join('')}</div></div>` : ''}
    <div class="card ${sc ? 'mt' : ''}"><h3>🎓 My certificates</h3>${certs.length ? certs.map((c) => `<div class="row li"><div class="sp"><b>${esc(c.title)}</b><div class="muted sm">${esc(c.serial)} · ${fdate(c.at)}</div></div><button class="btn s" data-act="printCert" data-id="${esc(c.id)}">Print</button></div>`).join('') : '<div class="muted">No certificates yet.</div>'}</div>
    <div class="card mt"><button class="btn r wide" data-act="signout">Sign out</button></div></div></div>`;
};
ACT.changePin = async () => { const v = Object.fromEntries(new FormData($('#pinform')).entries()); if (!/^\d{4}$/.test(v.nw)) return toast('The new PIN must be 4 digits.', true); if ((await hashPin(v.old, SESSION.salt)) !== SESSION.pinHash) return toast('The current PIN is not correct.', true); Object.assign(SESSION, await makeCred(v.nw)); audit('PIN changed', ''); commit(); $('#pinform').reset(); toast('PIN updated'); };
